### ISSUE TITLE
    "cName":"〖✟ŋีಖଏדЮ۞নმ௮✫₷ণજัゆ۩〗

### ISSUE THREAD

**Issue by wasborn** [wasborn/nunu_kap#2]
https://github.com/wasborn/nunu_kap/blob/fec7c06047647a0b2741c39ddea3544a8c3966c2/line-tcr.py#L144

**Comment by 69tonza69** [comment]
งง

**Comment by khomok1** [comment]
Traceback (most recent call last):
  File "bbc.py", line 9, in <module>
    cl.login(token="EnHM8JxZ3Ydutyryg3qb.lh9WH2MI6ZxzRP9ZZtzUcW.2gGmELRSCaskXwe2twpd280tycv2T3Vo6WvHbPYwVWg=")
  File "/data/data/com.termux/files/home/nunu_kap/LINETCR/LineApi.py", line 40, in login
    self.Poll = Poll(self.authToken)
  File "/data/data/com.termux/files/home/nunu_kap/LINETCR/Api/Poll.py", line 35, in __init__
    self.rev = self.client.getLastOpRevision()
  File "/data/data/com.termux/files/home/nunu_kap/LINETCR/Api/../lib/curve/LineService.py", line 9884, in getLastOpRevision
    return self.recv_getLastOpRevision()
  File "/data/data/com.termux/files/home/nunu_kap/LINETCR/Api/../lib/curve/LineService.py", line 9907, in recv_getLastOpRevision
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='Authentication Failed.', code=1)
